export const INSURANCE_PROVIDERS_INDIA = [
  "Star Health and Allied Insurance",
  "HDFC ERGO General Insurance",
  "ICICI Lombard General Insurance",
  "Niva Bupa Health Insurance",
  "Care Health Insurance",
  "Bajaj Allianz General Insurance",
  "Aditya Birla Health Insurance",
  "SBI General Insurance",
  "National Insurance Company",
  "New India Assurance",
  "Oriental Insurance",
  "United India Insurance",
  "ManipalCigna Health Insurance",
  "Reliance General Insurance",
  "Tata AIG General Insurance",
  "Cholamandalam MS General Insurance",
  "Digit Insurance",
  "Acko General Insurance",
  "Kotak Mahindra General Insurance",
  "Magma HDI General Insurance",
  "Universal Sompo General Insurance",
  "Future Generali India Insurance",
  "Navi General Insurance",
  "Other"
];
